---
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
      - aqua/reviewdog.yaml
  push:
    branches:
      - main
    paths:
      - .github/workflows/*.yaml
      - aqua/actionlint.yaml
      - aqua/reviewdog.yaml
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@6b8692cb5c9d3ffb2ff624ffeee3e10ae10615f3 # v1.1.0
    with:
      aqua_version: v2.36.0
    permissions:
      pull-requests: write
      contents: read
