name: test action
on: workflow_call
permissions: {}
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write # For reviewdog
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.55.2
      - run: npm ci
        working-directory: js
      - run: npm run build
        working-directory: js
      - uses: ./
        with:
          working_directory: tests/main
          github_comment: true
      - uses: ./
        with:
          working_directory: tests/old
          github_comment: true
